feat: big rewrite - v0.2.0

diff --git a/b2 b/b2
--- a/b2
+++ b/b2
@@ -1,104 +1,101 @@
 #!/bin/bash
 
-# b2 [BranchBuster] - A simple utility script that removes gone branches from the local repository.
+# b2 [BranchBuster] - A utility script that removes gone branches from the local repository.
 
-set -eou pipefail
+set -euo pipefail
 
-readonly VERSION="0.1.1"
+readonly VERSION="0.2.0"
 
 # Find gone git branches locally
-function find_gone_branches() {
-  git fetch -p || { echo "Failed to fetch from upstream. Aborting."; exit 1; }
-  git branch -vv \
-    | grep ': gone]' \
-    | grep -v "\*" \
-    | awk '{ print $1; }' \
-    | grep -v '^$' || true
+find_gone_branches() {
+  git fetch -p
+  git branch -vv | awk '/: gone]/{if ($1 != "*") print $1}'
 }
 
 # Delete gone branches from the local repository
-function delete_gone_branches() {
-  local branches=("$@")
+delete_gone_branches() {
+  set +e
   local branch
-  printf "\nDeleting the following branches:\n"
+  local branches=("$@")
+  echo -e "\nDeleting the following branches:"
+  printf '%s\n' "${branches[@]}"
   for branch in "${branches[@]}"; do
     git branch -D "$branch" || echo "Failed to delete branch: $branch"
   done
+  set -e
 }
 
 # Ask for user input to delete gone branches
-function ask_for_user_input() {
+ask_for_user_input() {
   local answer
   local gone_branches=("$@")
-  local main_prompt
-  local selection
-  local selected_branches=()
-
   echo "The following branches are gone:"
   for i in "${!gone_branches[@]}"; do
     echo "$((i + 1)). ${gone_branches[$i]}"
   done
 
-  main_prompt="Enter 'y' to delete all, 'n' to skip, or select by number: "
-
+  local main_prompt="Enter 'y' to delete all, 'n' to skip, or select by number: "
   while true; do
     read -r -p "$main_prompt" answer
-    if [[ "$answer" =~ ^[Yy] ]]; then
-      delete_gone_branches "${gone_branches[@]}"
-      break
-    elif [[ "$answer" =~ ^[Nn] ]]; then
-      echo "No branches deleted."
-      break
-    elif [[ "$answer" =~ ^[0-9]+( [0-9]+)*$ ]]; then
-      selection="$answer"
-      local number
-      for number in $selection; do
-        if ((number > 0 && number <= ${#gone_branches[@]})); then
-          selected_branches+=("${gone_branches[$((number - 1))]}")
+    case "$answer" in
+      [Yy])
+        delete_gone_branches "${gone_branches[@]}"
+        break
+        ;;
+      [Nn])
+        echo "No branches deleted."
+        break
+        ;;
+      *)
+        if [[ "$answer" =~ ^[0-9]+( [0-9]+)*$ ]]; then
+          local number
+          local selected_branches=()
+          for number in $answer; do
+            if ((number > 0 && number <= ${#gone_branches[@]})); then
+              selected_branches+=("${gone_branches[$((number - 1))]}")
+            else
+              echo "Invalid branch number: $number"
+            fi
+          done
+          if [ "${#selected_branches[@]}" -gt 0 ]; then
+            echo "You selected the following branches for deletion:"
+            printf '%s\n' "${selected_branches[@]}"
+            delete_gone_branches "${selected_branches[@]}"
+          else
+            echo "No valid selections made."
+          fi
+          break
         else
-          echo "Invalid branch number: $number"
+          echo "Invalid input. Please enter 'y', 'n', or branch numbers separated by spaces."
         fi
-      done
-
-      if [ "${#selected_branches[@]}" -gt 0 ]; then
-        echo "You selected the following branches for deletion:"
-        printf '%s\n' "${selected_branches[@]}"
-        delete_gone_branches "${selected_branches[@]}"
-      else
-        echo "No valid selections made."
-      fi
-      break
-    else
-      printf "%s" "Invalid input. Please enter 'y', 'n', " \
-                  "or branch numbers separated by spaces."
-    fi
+        ;;
+    esac
   done
 }
 
-# It just shows the version of the script
-function show_version() {
+# Show the version of the script
+show_version() {
   local current_year
   current_year=$(date +'%Y')
-  printf "\nb2 [BranchBuster] v%s (c) baduker %s\n" "$VERSION" "$current_year"
+  echo -e "\nb2 [BranchBuster] v$VERSION %s | coded by baduker" $current_year
 }
 
 # Main function
-function main() {
+main() {
   local line
-  local gone_branches=()
+  local gone_branches
   echo "Checking for gone branches..."
+  gone_branches=()
   while IFS= read -r line; do
-    if [[ -n "$line" ]]; then
-      gone_branches+=("$line")
-    fi
+    gone_branches+=("$line")
   done < <(find_gone_branches)
   if [ "${#gone_branches[@]}" -gt 0 ]; then
     ask_for_user_input "${gone_branches[@]}"
     show_version
   else
-    echo "No gone branches found!"
+    echo -e "\nNo gone branches found!"
     show_version
   fi
 }
 
-main
+main "$@"
